import React, { useState } from "react";
import { Sheet } from "@/components/ui/Sheet";
import { Button } from "@/components/ui/Button";

interface ExportDigestSheetProps {
  open: boolean;
  onClose: () => void;
}

const ExportDigestSheet: React.FC<ExportDigestSheetProps> = ({ open, onClose }) => {
  const [filename, setFilename] = useState("digest-2026-07-13");
  const [exportPath, setExportPath] = useState("C:/Users/Documents/Mercury/Digests");
  const [includeSummary, setIncludeSummary] = useState(true);
  const [includeNote, setIncludeNote] = useState(false);
  const [noteText, setNoteText] = useState("");
  const [summaryLanguage, setSummaryLanguage] = useState("zh-CN");
  const [detailLevel, setDetailLevel] = useState<"short" | "medium" | "detailed">("medium");
  const [summaryText, setSummaryText] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  // Placeholder article metadata
  const articleTitle = "Getting Started with Rust and Tauri";
  const articleAuthor = "Jane Doe";
  const articleUrl = "https://example.com/rust-tauri-guide";

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setSummaryText(
        "A comprehensive guide covering Rust and Tauri 2.0 for building " +
          "cross-platform desktop applications. Covers setup, architecture " +
          "patterns, and deployment strategies.",
      );
      setGenerating(false);
    }, 1500);
  };

  const buildMarkdown = () => {
    let md = `# ${articleTitle}`;
    if (articleAuthor) md += `\n\n*by ${articleAuthor}*`;
    md += `\n\n> Source: ${articleUrl}`;

    if (includeSummary && summaryText) {
      md += `\n\n## Summary\n\n${summaryText}`;
    }

    if (includeNote && noteText.trim()) {
      md += `\n\n## Notes\n\n${noteText}`;
    }

    md += `\n\n---\n*Generated by Mercury on ${new Date().toLocaleDateString()}*`;
    return md;
  };

  const markdown = buildMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdown);
  };

  const handleExport = () => {
    // TODO: invoke Tauri export command with filename and path
    console.log("Export to:", `${exportPath}/${filename}.md`);
  };

  return (
    <Sheet open={open} onClose={onClose} title="Export Digest" width="640px">
      <div className="space-y-4">
        {/* Article metadata */}
        <div className="p-3 bg-surface-secondary rounded-lg">
          <div className="text-sm font-medium text-slate-700">{articleTitle}</div>
          {articleAuthor && (
            <div className="text-xs text-slate-500 mt-0.5">by {articleAuthor}</div>
          )}
          <div className="text-xs text-slate-400 mt-0.5 truncate">{articleUrl}</div>
        </div>

        {/* Export filename */}
        <div>
          <label className="block text-xs font-medium text-slate-600 mb-1">
            Export Filename
          </label>
          <div className="flex items-center gap-1">
            <input
              type="text"
              value={filename}
              onChange={(e) => setFilename(e.target.value)}
              className="flex-1 h-8 px-2 text-sm rounded-md border border-border bg-surface focus:border-accent focus:outline-none"
            />
            <span className="text-sm text-slate-400">.md</span>
          </div>
        </div>

        {/* Export path */}
        <div>
          <label className="block text-xs font-medium text-slate-600 mb-1">
            Export Folder
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              readOnly
              value={exportPath}
              className="flex-1 h-8 px-2 text-sm rounded-md border border-border bg-surface-secondary text-slate-500 text-xs"
            />
            <Button variant="secondary" size="sm">Choose...</Button>
          </div>
        </div>

        {/* Summary section */}
        <div className="border border-border rounded-lg p-3 space-y-2">
          <h4 className="text-sm font-semibold text-slate-700">Summary</h4>
          <div className="flex gap-2">
            <select
              value={summaryLanguage}
              onChange={(e) => setSummaryLanguage(e.target.value)}
              className="h-7 px-1.5 text-xs rounded border border-border bg-surface focus:border-accent focus:outline-none"
            >
              <option value="zh-CN">Chinese</option>
              <option value="en">English</option>
              <option value="ja">Japanese</option>
            </select>
            <div className="flex gap-0.5 bg-surface-tertiary rounded p-0.5">
              {(["short", "medium", "detailed"] as const).map((dl) => (
                <button
                  key={dl}
                  onClick={() => setDetailLevel(dl)}
                  className={`px-2 py-0.5 text-[11px] font-medium rounded transition-colors ${
                    detailLevel === dl
                      ? "bg-surface text-slate-900 shadow-sm"
                      : "text-slate-500 hover:text-slate-700"
                  }`}
                >
                  {dl.charAt(0).toUpperCase() + dl.slice(1)}
                </button>
              ))}
            </div>
            <Button variant="secondary" size="sm" onClick={handleGenerate} loading={generating}>
              Generate
            </Button>
          </div>
          {summaryText && (
            <div className="text-sm text-slate-600 bg-surface-secondary rounded p-2">
              {summaryText}
            </div>
          )}
        </div>

        {/* Include note */}
        <label className="flex items-center gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={includeNote}
            onChange={(e) => setIncludeNote(e.target.checked)}
            className="rounded border-slate-300 text-accent w-3.5 h-3.5"
          />
          <span className="text-sm text-slate-700">Include note</span>
        </label>
        {includeNote && (
          <textarea
            value={noteText}
            onChange={(e) => setNoteText(e.target.value)}
            placeholder="Add a note to the export..."
            rows={3}
            className="w-full text-sm rounded-md border border-border bg-surface p-2 focus:border-accent focus:outline-none resize-none"
          />
        )}

        {/* Live Markdown preview */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Preview
          </label>
          <div className="p-3 bg-surface-secondary rounded-lg border border-border text-xs text-slate-600 whitespace-pre-wrap max-h-48 overflow-y-auto font-mono">
            {markdown}
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-2 pt-2 border-t border-border">
          <Button variant="secondary" size="md" onClick={onClose}>
            Cancel
          </Button>
          <Button variant="secondary" size="md" onClick={handleCopy}>
            Copy
          </Button>
          <Button variant="primary" size="md" onClick={handleExport}>
            Export
          </Button>
        </div>
      </div>
    </Sheet>
  );
};

export default ExportDigestSheet;
